<br>

#### 1. Import Libraries & Setup

In [1]:
import pandas as pd
import numpy as np

# Display settings for better readability in notebooks
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.options.display.max_rows = 10000

<br>

#### 2. Load Dataset

In [2]:
# Load Stack Overflow Survey dataset
df = pd.read_csv('Data/stack-overflow-developer-survey-2020/survey_results_public.csv')

# Preview first rows
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

<br>

#### 3. Initial Data Exploration

In [3]:
# View a random sample (transposed for better readability of all columns)
df.sample(1).T

                                                                          59527
Respondent                                                                60706
MainBranch                                       I am a developer by profession
Hobbyist                                                                     No
Age                                                                         NaN
Age1stCode                                                                   22
CompFreq                                                                    NaN
CompTotal                                                                   NaN
ConvertedComp                                                               NaN
Country                                                           United States
CurrencyDesc                                                                NaN
CurrencySymbol                                                              NaN
DatabaseDesireNextYear                                                      NaN
DatabaseWorkedWith                                                          NaN
DevType                                                   Developer, full-stack
EdLevel                            Bachelor’s degree (B.A., B.S., B.Eng., etc.)
Employment                                                   Employed full-time
Ethnicity                                                                   NaN
Gender                                                                      NaN
JobFactors                                                                  NaN
JobSat                                                                      NaN
JobSeek                                                                     NaN
LanguageDesireNextYear                                                      NaN
LanguageWorkedWith                                                          NaN
MiscTechDesireNextYear                                                      NaN
MiscTechWorkedWith                                                          NaN
NEWCollabToolsDesireNextYear                                                NaN
NEWCollabToolsWorkedWith                                                    NaN
NEWDevOps                                                                   NaN
NEWDevOpsImpt                                                               NaN
NEWEdImpt                                                        Very important
NEWJobHunt                                                                  NaN
NEWJobHuntResearch                                                          NaN
NEWLearn                                                                    NaN
NEWOffTopic                                                                 NaN
NEWOnboardGood                                                              NaN
NEWOtherComms                                                               Yes
NEWOvertime                                                                 NaN
NEWPurchaseResearch                                                         NaN
NEWPurpleLink                                                               NaN
NEWSOSites                    Stack Overflow (public Q&A for anyone who code...
NEWStuck                                                                    NaN
OpSys                                                                       NaN
OrgSize                                                                     NaN
PlatformDesireNextYear                                                      NaN
PlatformWorkedWith                                                          NaN
PurchaseWhat                                                                NaN
Sexuality                                                                   NaN
SOAccount                                                                    No
SOComm                                                           No, not at all
SOPartFreq                                                                  NaN
SOVisitFreq                                                A few times per week
SurveyEase                                                                  NaN
SurveyLength                                                                NaN
Trans                                                                       NaN
UndergradMajor                                                              NaN
WebframeDesireNextYear                                                      NaN
WebframeWorkedWith                                                          NaN
WelcomeChange                                                               NaN
WorkWeekHrs                                                                 NaN
YearsCode                                                                     5
YearsCodePro                                                                  3

In [4]:
# Get dataset structure and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Respondent                    64461 non-null  int64
 1   MainBranch                    64162 non-null  object
 2   Hobbyist                      64416 non-null  object
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object
 5   CompFreq                      40069 non-null  object
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object
 9   CurrencyDesc                  45472 non-null  object
 10  CurrencySymbol                45472 non-null  object
 11  DatabaseDesireNextYear        44070 non-null  object
 12  DatabaseWorkedWith            49537 non-null  object
 13  DevType                       49370 non-null  object
 14  EdLevel                       57431 non-null  object
 15  Employment                    63854 non-null  object
 16  Ethnicity                     45948 non-null  object
 17  Gender                        50557 non-null  object
 18  JobFactors                    49349 non-null  object
 19  JobSat                        45194 non-null  object
 20  JobSeek                       51727 non-null  object
 21  LanguageDesireNextYear        54113 non-null  object
 22  LanguageWorkedWith            57378 non-null  object
 23  MiscTechDesireNextYear        42379 non-null  object
 24  MiscTechWorkedWith            40314 non-null  object
 25  NEWCollabToolsDesireNextYear  47287 non-null  object
 26  NEWCollabToolsWorkedWith      52883 non-null  object
 27  NEWDevOps                     42686 non-null  object
 28  NEWDevOpsImpt                 41732 non-null  object
 29  NEWEdImpt                     48465 non-null  object
 30  NEWJobHunt                    42286 non-null  object
 31  NEWJobHuntResearch            41022 non-null  object
 32  NEWLearn                      56156 non-null  object
 33  NEWOffTopic                   50804 non-null  object
 34  NEWOnboardGood                42623 non-null  object
 35  NEWOtherComms                 57205 non-null  object
 36  NEWOvertime                   43231 non-null  object
 37  NEWPurchaseResearch           37321 non-null  object
 38  NEWPurpleLink                 54803 non-null  object
 39  NEWSOSites                    58275 non-null  object
 40  NEWStuck                      54983 non-null  object
 41  OpSys                         56228 non-null  object
 42  OrgSize                       44334 non-null  object
 43  PlatformDesireNextYear        50605 non-null  object
 44  PlatformWorkedWith            53843 non-null  object
 45  PurchaseWhat                  39364 non-null  object
 46  Sexuality                     43992 non-null  object
 47  SOAccount                     56805 non-null  object
 48  SOComm                        56476 non-null  object
 49  SOPartFreq                    46792 non-null  object
 50  SOVisitFreq                   56970 non-null  object
 51  SurveyEase                    51802 non-null  object
 52  SurveyLength                  51701 non-null  object
 53  Trans                         49345 non-null  object
 54  UndergradMajor                50995 non-null  object
 55  WebframeDesireNextYear        40024 non-null  object
 56  WebframeWorkedWith            42279 non-null  object
 57  WelcomeChange                 52683 non-null  object
 58  WorkWeekHrs                   41151 non-null  float64
 59  YearsCode                     57684 non-null  object
 60  YearsCodePro                  46349 non-null  object
dtypes: float64(4), int64(1), object(56)
memory usage: 30.0+ MB

####  Initial Observations

- The dataset contains a large number of features (~60+ columns)
- Many columns have `object` data types (categorical/text data)
- There are significant missing values across multiple columns

 This indicates that data cleaning and feature selection will be important steps.

<br>

##### &emsp; &emsp; 3.1 Dropping Irrelevant Columns

In [5]:
# Dropping columns that are not relevant to our problem:
# Goal: Focus on relationships between job roles and technologies

df_clean = df.drop(columns=[
    'Hobbyist','CompFreq','CompTotal','CurrencyDesc','Ethnicity','Gender',
    'JobSat','JobSeek','NEWJobHunt','NEWJobHuntResearch','NEWLearn',
    'NEWOffTopic','NEWOnboardGood','NEWOtherComms','NEWOvertime',
    'NEWPurchaseResearch','NEWPurpleLink','NEWStuck','OpSys',
    'PurchaseWhat','Sexuality','SOAccount','SOComm','SOPartFreq',
    'SOVisitFreq','SurveyEase','SurveyLength','Trans','WelcomeChange',
    'WorkWeekHrs'
])

# Preview cleaned dataset
df_clean.head()

,Respondent,MainBranch,Age,Age1stCode,ConvertedComp,Country,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,...,NEWEdImpt,NEWSOSites,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,YearsCode,YearsCodePro
0,1,I am a developer by profession,NaN,13,NaN,Germany,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...",...,Fairly important,Stack Overflow (public Q&A for anyone who codes),2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,36,27
1,2,I am a developer by profession,NaN,19,NaN,United Kingdom,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile",...,Fairly important,Stack Overflow (public Q&A for anyone who code...,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,"Computer science, computer engineering, or sof...",NaN,NaN,7,4
2,3,I code primarily as a hobby,NaN,15,NaN,Russian Federation,NaN,NaN,NaN,NaN,...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,4,NaN
3,4,I am a developer by profession,25.0,18,NaN,Albania,ALL,NaN,NaN,NaN,...,Not at all important/not necessary,Stack Overflow (public Q&A for anyone who code...,20 to 99 employees,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,7,4
4,5,"I used to be a developer by profession, but no...",31.0,16,NaN,United States,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,...,Very important,Stack Overflow (public Q&A for anyone who code...,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,15,8

####  Feature Selection Strategy

Since the goal of this project is to understand the relationship between:
- Job roles
- Technologies (languages, tools, frameworks)

We removed columns related to:
- Personal demographics (e.g., Gender, Ethnicity)
- Survey experience (e.g., SurveyEase, SurveyLength)
- Job satisfaction and preferences
- Compensation-related data

 This helps simplify the dataset and keeps the analysis focused.

 Note: Dropped columns can be reintroduced later if needed.