## 1. Import Libraries

In [1]:
import pandas as pd
from scipy.stats import zscore

<br>

## 2. Load Dataset

In [2]:
# Load preprocessed dataset from previous notebook
df=pd.read_pickle('../Data/processed_data/processed_data.pkl')

df.head()

,skills,DevType
0,"[Microsoft SQL Server, Elasticsearch, Oracle, ...","[desktop or enterprise applications, full-stack]"
1,"[Python, Swift, JavaScript, React Native, Tens...","[full-stack, mobile]"
2,"[HTML/CSS, Java, JavaScript, React.js]","[Designer, front-end, mobile]"
3,"[MongoDB, MariaDB, MySQL, Redis, JavaScript, P...","[back-end, desktop or enterprise applications,..."
4,"[Python, Rust, HTML/CSS, JavaScript, PHP, Angu...",[full-stack]

<br>

## 3. One-Hot Encoding

### Objective

- Convert multi-label columns (`skills`, `DevType`) into a machine-learning-ready format using one-hot encoding.

- This step prepares the dataset for modeling

In [3]:
# Function to extract all unique values from a multi-label column

def get_unique_values(column):
    unique_values = set()
    for row in column:
        for value in row:
            unique_values.add(value)
    unique_values_list = list(unique_values)
    unique_values_list.sort(key=str.lower)
    return unique_values_list

In [4]:
# Function to perform one-hot encoding on a multi-label column
# Creates binary columns for each unique value (1 if present, else 0).

# Returns: a list of generated column names.
# which can later be used to separate feature columns from target columns.
def one_hot_encode(column):
    unique_values  = get_unique_values(column)

    # initialize all new columns with 0
    df[unique_values] = 0
    
    # fill columns with 1 if the value exists in the row, else 0
    for col in unique_values:
        df[col] = column.apply(lambda x:1 if col in x else 0)

    # return column names (useful later to separate features and target)
    return unique_values

In [5]:
# Apply one-hot encoding on the 'skills' column
# and returns the list of generated feature column names
feature_columns  = one_hot_encode(df['skills'])

# Display feature columns
df[feature_columns].head()

,.NET,.NET Core,Angular,Angular.js,Ansible,Apache Spark,ASP.NET,ASP.NET Core,Assembly,Bash/Shell/PowerShell,...,Symfony,TensorFlow,Teraform,Torch/PyTorch,TypeScript,Unity 3D,Unreal Engine,VBA,Vue.js,Xamarin
0,1,1,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# Apply one-hot encoding on the 'DevType' column
# and returns the list of generated Target column names
target_columns  = one_hot_encode(df['DevType'])

# Display target columns
df[target_columns]

,Academic researcher,back-end,Data or business analyst,Data scientist or machine learning specialist,Database administrator,Designer,desktop or enterprise applications,DevOps specialist,Educator,embedded applications or devices,...,front-end,full-stack,game or graphics,Marketing or sales professional,mobile,Product manager,QA or test,Scientist,Senior executive/VP,System administrator
0,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,0,1,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
36999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
37000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
37001,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37002,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# Remove original multi-label columns after encoding
# They are no longer needed since we now have one-hot encoded features
df.drop(columns=['skills', 'DevType'], inplace=True)

# Verify the result
df.head()

,.NET,.NET Core,Angular,Angular.js,Ansible,Apache Spark,ASP.NET,ASP.NET Core,Assembly,Bash/Shell/PowerShell,...,front-end,full-stack,game or graphics,Marketing or sales professional,mobile,Product manager,QA or test,Scientist,Senior executive/VP,System administrator
0,1,1,0,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

<br>

## 4. Feature Scaling

### Objective

Standardize feature values to ensure they are on a comparable scale.<br>

Although one-hot encoded features are binary (0/1), scaling is applied here to maintain consistency across all features and prepare the dataset for models sensitive to feature magnitude.

We will use Z-score normalization:
- Mean = 0
- Standard deviation = 1

In [8]:
# Apply Z-score standardization on feature columns
df[feature_columns]=df[feature_columns].apply(zscore)
df.head()

,.NET,.NET Core,Angular,Angular.js,Ansible,Apache Spark,ASP.NET,ASP.NET Core,Assembly,Bash/Shell/PowerShell,...,front-end,full-stack,game or graphics,Marketing or sales professional,mobile,Product manager,QA or test,Scientist,Senior executive/VP,System administrator
0,1.724315,1.762893,-0.569413,-0.416451,-0.289751,-0.27559,2.257887,2.082232,-0.228229,-0.716789,...,0,1,0,0,0,0,0,0,0,0
1,-0.579940,-0.567249,-0.569413,-0.416451,-0.289751,-0.27559,-0.442892,-0.480254,-0.228229,-0.716789,...,0,1,0,0,1,0,0,0,0,0
2,-0.579940,-0.567249,-0.569413,-0.416451,-0.289751,-0.27559,-0.442892,-0.480254,-0.228229,-0.716789,...,1,0,0,0,1,0,0,0,0,0
3,-0.579940,-0.567249,-0.569413,-0.416451,3.451235,-0.27559,-0.442892,-0.480254,-0.228229,-0.716789,...,0,0,1,0,0,0,0,0,0,0
4,-0.579940,-0.567249,-0.569413,2.401240,-0.289751,-0.27559,-0.442892,-0.480254,-0.228229,-0.716789,...,0,1,0,0,0,0,0,0,0,0

<br>

## 5. Saving ML-Ready Dataset <br>


### Objective

Save the fully transformed dataset after:
- One-hot encoding
- Feature scaling

This dataset is now fully numeric and ready for machine learning modeling.

The final version is stored as a pickle file (.pkl) for efficient loading in the modeling notebook.

In [9]:
# Save the final ML-ready dataset
df.to_pickle('../Data/processed_data/ml_ready_data.pkl')

# Save feature and target columns separately (cleaner for modeling)
X = df[feature_columns]
y = df[target_columns]

X.to_pickle('../Data/processed_data/X_features.pkl')
y.to_pickle('../Data/processed_data/y_targets.pkl')